AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack that creates three nested stacks (VPC, IAM, App)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
  InstanceType:
    Type: String
    Default: t3.micro
  MinSize:
    Type: Number
    Default: 1
  DesiredCapacity:
    Type: Number
    Default: 2
  MaxSize:
    Type: Number
    Default: 3

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://nested-stack-yaml.s3.ap-south-1.amazonaws.com/vpc.yaml"  # <-- upload vpc.yaml and set this URL
      Parameters:
        VpcCidr: 10.0.0.0/16

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://nested-stack-yaml.s3.ap-south-1.amazonaws.com/iam.yaml"  # <-- upload iam.yaml and set this URL
      Parameters:
        InstanceRoleName: cf-app-ec2-role

  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://nested-stack-yaml.s3.ap-south-1.amazonaws.com/app.yaml"  # <-- upload app.yaml and set this URL
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnet1: !GetAtt VpcStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VpcStack.Outputs.PublicSubnet2
        InstanceProfileName: !GetAtt IAMStack.Outputs.InstanceProfileName
        KeyName: !Ref KeyName
        SSHLocation: !Ref SSHLocation
        InstanceType: !Ref InstanceType
        MinSize: !Ref MinSize
        DesiredCapacity: !Ref DesiredCapacity
        MaxSize: !Ref MaxSize

Outputs:
  AppLoadBalancerDNS:
    Description: ALB DNS (from nested AppStack)
    Value: !GetAtt AppStack.Outputs.LoadBalancerDNS
