AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch Monitoring & Logging for ALB, ASG (EC2), RDS

Parameters:
  AlarmEmail:
    Type: String
    Description: Email address to receive alarm notifications
  MyASG:
    Type: String
  ALBDNS:
    Type: String
  RDSId:
    Type: String
  AppName:                       
    Type: String
  Environment:                   
    Type: String

  
Resources:
  ### SNS Topic for Notifications ###
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AppName}-${Environment}-monitoring-sns"   
      Tags:                                                       
        - Key: Name
          Value: !Sub "${AppName}-${Environment}-monitoring-sns"
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  AlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref AlarmEmail
      TopicArn: !Ref AlarmTopic

  ### ASG CPU Utilization Alarm ###
  ASGHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AppName}-${Environment}-asg-highcpu"
      Namespace: "AWS/EC2"
      MetricName: CPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref MyASG   # 👈 Replace with your ASG logical ID from same stack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 45
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      Tags:                                                       
        - Key: Name
          Value: !Sub "${AppName}-${Environment}-asg-highcpu"
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  ### RDS Free Storage Space Alarm ###
  RDSLowStorageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AppName}-${Environment}-rds-lowstorage"
      Namespace: "AWS/RDS"
      MetricName: FreeStorageSpace
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RDSId   # Replace with your RDS DB identifier
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10000000000 # 10GB
      ComparisonOperator: LessThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      Tags:                                                       
        - Key: Name
          Value: !Sub "${AppName}-${Environment}-rds-lowstorage"
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  ### ALB 5XX Errors Alarm ###
  ALB5XXAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AppName}-${Environment}-alb-5xx" 
      Namespace: "AWS/ApplicationELB"
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBDNS   # 👈 Dynamic from root
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic
      Tags:                                                       
        - Key: Name
          Value: !Sub "${AppName}-${Environment}-alb-5xx"
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Environment

  ### CloudWatch Dashboard ###
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${AppName}-${Environment}-monitoring-dashboard" 
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/EC2", "CPUUtilization", "AutoScalingGroupName", "${MyASG}" ]
                ],
                "region": "${AWS::Region}",
                "title": "ASG CPU Utilization",
                "period": 300,
                "stat": "Average"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/RDS", "FreeStorageSpace", "DBInstanceIdentifier", "${RDSId}" ]
                ],
                "region": "${AWS::Region}",
                "title": "RDS Free Storage Space",
                "period": 300,
                "stat": "Average"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApplicationELB", "HTTPCode_ELB_5XX_Count", "LoadBalancer", "${ALBDNS}" ]
                ],
                "region": "${AWS::Region}",
                "title": "ALB 5XX Errors",
                "period": 300,
                "stat": "Sum"
              }
            }
          ]
        }

Outputs:
  AlarmTopicArn:
    Description: SNS Topic ARN for Monitoring Alarms
    Value: !Ref AlarmTopic
    Export:
      Name: Monitoring-AlarmTopicArn

  DashboardName:
    Description: Name of the CloudWatch Dashboard
    Value: !Ref MonitoringDashboard
    Export:
      Name: Monitoring-DashboardName