AWSTemplateFormatVersion: "2010-09-09"
Description: "Nested stack for SSM Parameters (CloudWatch agent config + DB secret reference)"

Parameters:
  AppName:                       
    Type: String
  Environment:                   
    Type: String

Resources:
  CloudWatchAgentConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /ec2/cloudwatch/agent/config
      Type: String
      Value: !Sub |
        {
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/home/ec2-user/app/logs/*.log",
                    "log_group_name": "/ec2/backend/logs",
                    "log_stream_name": "{instance_id}/backend",
                    "timezone": "UTC"
                  },
                  {
                    "file_path": "/home/ec2-user/.pm2/logs/*.log",
                    "log_group_name": "/ec2/pm2/logs",
                    "log_stream_name": "{instance_id}/pm2",
                    "timezone": "UTC"
                  }
                ]
              }
            },
            "log_stream_name": "ec2-{instance_id}",
            "force_flush_interval": 15
          }
        }
      Tags:
        Name: !Sub "${AppName}-${Environment}-ec2-ssmparam"
        Application: !Ref AppName
        Environment: !Ref Environment

Outputs:
  CloudWatchAgentConfigParam:
    Value: !Ref CloudWatchAgentConfig
    Export:
      Name: !Sub "${AWS::StackName}-CloudWatchAgentConfig"
