AWSTemplateFormatVersion: "2010-09-09"
Description: "Nested Stack — Aurora MySQL Cluster"

Parameters:
  VpcId:
    Type: String
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  DatabaseName:
    Type: String
    Default: tododb
  DBSecurityGroup:
    Type: String
  BackendDbSecret:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Aurora Subnet Group"
      SubnetIds: !Ref SubnetIds

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: "8.0.mysql_aurora.3.05.2"
      DBClusterIdentifier: my-aurora-cluster
      MasterUsername: !Join 
        - ''
        - ['{{resolve:secretsmanager:', !Ref BackendDbSecret, ':SecretString:username}}']
      MasterUserPassword: !Join
        - ''
        - ['{{resolve:secretsmanager:', !Ref BackendDbSecret, ':SecretString:password}}']
      DBSubnetGroupName: !Ref DBSubnetGroup
      DatabaseName: !Ref DatabaseName
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      DeletionProtection: false

  AuroraInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: AuroraEndpoint
