version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CLI if not present..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install --update

  pre_build:
    commands:
      - echo "Starting pre-build..."
      - 'export BUCKET_NAME=$ARTIFACT_BUCKET'
      - 'echo "Bucket is: $BUCKET_NAME"'

  build:
    commands:
      - echo "Packaging nested stacks..."
      - aws s3 cp ./templates/nested-stack/mysql-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/aurora-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/vpc-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/security-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/ssm-parameters-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/monitoring-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/backend-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/frontend-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - aws s3 cp ./templates/nested-stack/role-template.yaml s3://$BUCKET_NAME/ --region $AWS_DEFAULT_REGION
      - echo "Nested stacks uploaded successfully."

  post_build:
    commands:
      - echo "Preparing artifacts for CloudFormation..."
      - mkdir -p output
      - cp templates/root-template-main.yaml output/
      - echo "Build completed on `date`"

artifacts:
  files:
    - output/root-template-main.yaml
  discard-paths: yes
